# Generated by Django 3.2 on 2023-06-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('task', 'team')},
        ),
    ]
